{{ if not .Values.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: "artifacts-credentials"
  namespace: {{ .Values.config.kubernetes.namespace }}
type: Opaque
data:
  credentials: {{ .Values.config.objectStorage.credential | b64enc | indent 2 }}
{{ end }}