apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "runner.fullname" . }}
  labels:
    {{- include "runner.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "runner.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "runner.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ include "runner.fullname" . }}-image-registry
      serviceAccountName: {{ include "runner.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: ["/app/runner"]
          args: ["--config", "/config/config.yaml", "--debug", "true"]
          env:
            - name: RQLITE_HOST
              value: {{ include "rqlite.fullname" . }}-svc
            - name: RQLITE_PORT
              value: "4001"
            - name: TASK_IMAGE_PULL_SECRET_NAME
              value: {{ include "runner.fullname" . }}-image-registry
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: secret
              mountPath: "/config"
              readOnly: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: secret
          secret:
            secretName: {{ include "runner.fullname" . }}
            items:
              - key: config
                path: config.yaml