apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "rqlite.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "rqlite.name" . }}
  serviceName: {{ include "rqlite.fullname" . }}-svc-internal
  replicas: {{ .Values.rqlite.replicaCount }}
  podManagementPolicy: "Parallel"
  template:
    metadata:
      labels:
        app: {{ include "rqlite.name" . }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: 10
      containers:
        - name: {{ include "rqlite.name" . }}
          image: {{ .Values.rqlite.image.repository }}:{{ .Values.rqlite.image.tag }}
          imagePullPolicy: {{ .Values.rqlite.image.pullPolicy }}
          args:
            - "-disco-mode=dns"
            - "-disco-config={\"name\":\"{{ include "rqlite.fullname" . }}-svc-internal\"}"
            - "-bootstrap-expect={{ .Values.rqlite.replicaCount }}"
            - "-join-interval=1s"
            - "-join-attempts=120"
          ports:
            - containerPort: 4001
              name: rqlite
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /readyz
              port: 4001
            periodSeconds: 5
            timeoutSeconds: 2
            initialDelaySeconds: 2
          livenessProbe:
            httpGet:
              scheme: HTTP
              path: /readyz?noleader
              port: rqlite
            initialDelaySeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
          volumeMounts:
            - name: rqlite-file
              mountPath: /rqlite/file
  volumeClaimTemplates:
    - metadata:
        name: rqlite-file
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: {{ .Values.rqlite.storageSize }}
