apiVersion: v1
kind: Service
metadata:
  name: {{ include "rqlite.fullname" . }}-svc-internal
spec:
  clusterIP: None
  publishNotReadyAddresses: True
  selector:
    app: {{ include "rqlite.name" . }}
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
