apiVersion: v1
kind: Service
metadata:
  name: {{ include "rqlite.fullname" . }}-svc
spec:
  selector:
    app: {{ include "rqlite.name" . }}
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4001
