{{ if not .Values.useExistingConfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "runner.fullname" . }}
  namespace: {{ .Release.Namespace }}
type: Generic
data:
  config: |
{{ .Values.config | toYaml | toString | b64enc | indent 4 }}
{{ end }}
